name: Hello-world
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: codebuild-GitHubSelfHosted-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: |
          echo "running on CodeBuild..."
          echo "OS: $(uname -a)"
          aws sts get-caller-identity
